-- psql -d srrf

-- DROP TABLE OPERATOR;
-- DROP TABLE CONTROLLER;
-- DROP TABLE OPERATOR_CONTROLLER;
-- DROP TABLE CLIENTE;
-- DROP TABLE CLIENTE_PICTURE;
-- DROP TABLE CATEGORIE;
-- DROP TABLE PRODUCT;
-- DROP TABLE PRODUCT_PICTURE;
-- DROP TABLE CLIENTE_PRODUCT;

CREATE TABLE IF NOT EXISTS OPERATOR (
	PK_OPERATOR serial,
	name text,
	telefone text,
	cpf text,
	email text,
	login text,
	password text,
	pass_hash text,
	inactive numeric(9,2),
	PRIMARY KEY(PK_OPERATOR )
);

CREATE TABLE IF NOT EXISTS CONTROLLER (
	PK_CONTROLLER serial,
	controller text,
	\"default\" text,
	PRIMARY KEY(PK_CONTROLLER )
);

CREATE TABLE IF NOT EXISTS OPERATOR_CONTROLLER(
    PK_OPERATOR INTEGER,
    PK_CONTROLLER INTEGER,
    FOREIGN KEY (PK_OPERATOR) REFERENCES OPERATOR(PK_OPERATOR),
    FOREIGN KEY (PK_CONTROLLER) REFERENCES CONTROLLER(PK_CONTROLLER)
);
CREATE TABLE IF NOT EXISTS CLIENTE(
	PK_CLIENTE SERIAL,
	NAME TEXT,
	EMAIL TEXT,
	TELEFONE TEXT,
	CPF TEXT,
	PRIMARY KEY(PK_CLIENTE)
);
CREATE TABLE IF NOT EXISTS CLIENTE_PICTURE(
	PK_CLIENTE_PICTURE SERIAL,
	PK_CLIENTE INTEGER,
	PICTURE TEXT,
    PRIMARY KEY (PK_CLIENTE_PICTURE),
    FOREIGN KEY (PK_CLIENTE) REFERENCES CLIENTE(PK_CLIENTE)
);

CREATE TABLE IF NOT EXISTS CATEGORIE(
    PK_CATEGORIE SERIAL,
    CATEGORIE TEXT,
    \"DEFAULT\" INTEGER,
    PRIMARY KEY(PK_CATEGORIE)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
    PK_PRODUCT SERIAL,
    PRODUCT TEXT,
    DESCRIPTION TEXT,
    INACTIVE INTEGER,
    PRIMARY KEY(PK_PRODUCT)
);
CREATE TABLE IF NOT EXISTS PRODUCT_PICTURE(
    PK_PRODUCT_PICTURE SERIAL,
    PK_PRODUCT INTEGER,
    PICTURE TEXT,
    PRIMARY KEY (PK_PRODUCT_PICTURE),
    FOREIGN KEY (PK_PRODUCT) REFERENCES PRODUCT(PK_PRODUCT)
);

CREATE TABLE IF NOT EXISTS CLIENTE_PRODUCT(
    PK_CLIENTE_PRODUCT SERIAL,
    PK_CLIENTE INTEGER,
    PK_PRODUCT INTEGER,
    PRIMARY KEY (PK_CLIENTE_PRODUCT),
    FOREIGN KEY(PK_CLIENTE) REFERENCES CLIENTE(PK_CLIENTE),
    FOREIGN KEY(PK_PRODUCT) REFERENCES PRODUCT(PK_PRODUCT)
);